name: Deploy Node.js App after each commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Self Hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          path: oh-dev-reusable-asset

      - name: Setup up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install