name: Deploy Node.js App after each commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Self Hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
          with:
            path: ~/Development/OwlsHead/oh-dev-reusable-asset/test

      - name: Setup up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Start App
        run: pm2 start npm -- run start



      